server:
  address: 0.0.0.0
  port: 8083

spring:
  rsocket:
    server:
      transport: tcp
      port: 6503

  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: INFO

  file:
    name: log.log